title: <%= projectName %>
description: <%= description %>

# Build settings
markdown: kramdown
exclude: ["README.md", "Gruntfile.js", "changelog.md", "Gemfile", "Gemfile.lock", "node_modules", "bower_components", "scss", "config.rb", "package.json", "LICENSE-MIT", "bower.json"]

gems:
  - jekyll-sitemap

